# Generated by Django 5.1.6 on 2025-02-07 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_facturas', '0001_initial'),
        ('gestion_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_envio', models.CharField(choices=[('Correo', 'Correo'), ('WhatsApp', 'WhatsApp'), ('Físico', 'Físico')], max_length=50)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('id_factura', models.ForeignKey(db_column='id_factura', on_delete=django.db.models.deletion.CASCADE, to='gestion_facturas.factura')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.usuario')),
            ],
            options={
                'db_table': 'envio_factura',
            },
        ),
    ]
